@url = http://127.0.0.1:3004/v1

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVybnN0QGdtYWlsLmNvbSIsImlkIjoxLCJ1c2VybmFtZSI6ImVybnN0IiwiaWF0IjoxNzEzODEyMDgwLCJleHAiOjE3MTM4OTg0ODB9.VVCRG2qBd-ilyvleN5BiCXBltyaFRF6f7erbNlV7xx4

###
POST {{url}}/user/login
Content-Type: application/json

{
    "email":"Liam1@gmail.com",
    "password":"Liam123!"
} 

###

POST {{url}}/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImVtYWlsIjoiTGlhbTFAZ21haWwuY29tIiwic3RhdGUiOiI5YmZkYWY0ZTI4M2E4ZWIyODQxNTEwYzMyZmExN2RjMiIsImlhdCI6MTcxMzg4MDk1OSwiZXhwIjoxNzEzOTY3MzU5fQ.8zFzhmfU8YAlPEjaNM2vVPTFzurHjF0TaGSyD0nrVqY"
}


###

POST {{url}}/refresh
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImVtYWlsIjoiTGlhbTFAZ21haWwuY29tIiwic3RhdGUiOiI5YmZkYWY0ZTI4M2E4ZWIyODQxNTEwYzMyZmExN2RjMiIsImlhdCI6MTcxMzg4MDk1OSwiZXhwIjoxNzEzOTY3MzU5fQ.8zFzhmfU8YAlPEjaNM2vVPTFzurHjF0TaGSyD0nrVqY"
}

###

DELETE  {{url}}/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImVtYWlsIjoiTGlhbTFAZ21haWwuY29tIiwic3RhdGUiOiI5YmZkYWY0ZTI4M2E4ZWIyODQxNTEwYzMyZmExN2RjMiIsImlhdCI6MTcxMzg4MDk1OSwiZXhwIjoxNzEzOTY3MzU5fQ.8zFzhmfU8YAlPEjaNM2vVPTFzurHjF0TaGSyD0nrVqY"
}
