@url = http://127.0.0.1:3004/v1

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVybnN0QGdtYWlsLmNvbSIsImlkIjoxLCJ1c2VybmFtZSI6ImVybnN0IiwiaWF0IjoxNzEzODEyMDgwLCJleHAiOjE3MTM4OTg0ODB9.VVCRG2qBd-ilyvleN5BiCXBltyaFRF6f7erbNlV7xx4

###
POST {{url}}/user/login
Content-Type: application/json

{
  "email":"ernst@gmail.com",
    "password":"a"
} 

###

POST {{url}}/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTEsImVtYWlsIjoiYWRtaW5AYWRtaW4iLCJzdGF0ZSI6ImRhMWYzNDI3ZTYxN2M3Mjg1ZWU4OTg5MGUyYTNkN2U3IiwidXNlcl9zdGF0dXMiOiJub3QgYWN0aXZlIiwiaWF0IjoxNjkwMzYwNDQ3LCJleHAiOjE2OTA0NDY4NDd9.XxPOyhw5YpJm8OJyPj_DODEoPToONFMniVNNq2LtHC4"
}


###

POST {{url}}/refresh
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTEsImVtYWlsIjoiYWRtaW5AYWRtaW4iLCJzdGF0ZSI6ImRhMWYzNDI3ZTYxN2M3Mjg1ZWU4OTg5MGUyYTNkN2U3IiwidXNlcl9zdGF0dXMiOiJub3QgYWN0aXZlIiwiaWF0IjoxNjkwMzYwNDQ3LCJleHAiOjE2OTA0NDY4NDd9.XxPOyhw5YpJm8OJyPj_DODEoPToONFMniVNNq2LtHC4"
}

###

DELETE  {{url}}/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTEsImVtYWlsIjoiYWRtaW5AYWRtaW4iLCJzdGF0ZSI6ImRhMWYzNDI3ZTYxN2M3Mjg1ZWU4OTg5MGUyYTNkN2U3IiwidXNlcl9zdGF0dXMiOiJub3QgYWN0aXZlIiwiaWF0IjoxNjkwMzYwNDQ3LCJleHAiOjE2OTA0NDY4NDd9.XxPOyhw5YpJm8OJyPj_DODEoPToONFMniVNNq2LtHC4"
}
